"""
NEXUS STATION - Stellar Outreach Game Module

Gamified space education platform integrating real astronomical data
with interactive discovery mechanics.
"""

from narrative_agentic.stellar_outreach.discovery_cards import (
    DiscoveryCard,
    CardCollection,
    fetch_daily_card,
    get_card_collection,
    collect_card,
)

from narrative_agentic.stellar_outreach.birth_chart import (
    BirthChartInput,
    PlanetPosition,
    NatalChart,
    ZodiacArchetype,
    PlayerProfile,
    calculate_birth_chart,
    player_profile_to_dict,
)

from narrative_agentic.stellar_outreach.transit_engine import (
    TransitSnapshot,
    TransitPlanetPosition,
    AspectHit,
    ModuleStatus,
    CosmicBriefing,
    get_transit_snapshot,
    calculate_player_transits,
    generate_briefing_text,
    cosmic_briefing_to_dict,
    transit_snapshot_to_dict,
)

from narrative_agentic.stellar_outreach.station_modules import (
    StationModule,
    PlayerStation,
    create_station,
    get_station,
    save_station,
    apply_cosmic_status,
    collect_resources,
    upgrade_module,
    get_module_info,
    station_to_dict,
)

from narrative_agentic.stellar_outreach.mini_games import (
    ConstellationPuzzle,
    StarPatternResult,
    RepairGrid,
    RepairResult,
    AsteroidScenario,
    DeflectionResult,
    DailyMission,
    generate_star_puzzle,
    score_star_puzzle,
    generate_repair_puzzle,
    validate_repair_solution,
    generate_asteroid_scenario,
    score_deflection,
    generate_daily_mission,
    daily_mission_to_dict,
)

from narrative_agentic.stellar_outreach.cosmic_briefing import (
    DailyBriefingData,
    generate_daily_briefing,
    get_cached_briefing,
    briefing_to_dict,
    get_element_colors,
    ELEMENT_COLORS,
)

from narrative_agentic.stellar_outreach.notifications import (
    NotificationPayload,
    NotificationPreferences,
    NotificationHistory,
    generate_morning_briefing,
    generate_event_notification,
    generate_re_engagement,
    can_send_notification,
    get_preferences,
    update_preferences,
    record_app_open,
    get_notification_history,
    mark_notification_read,
    get_daily_count,
    notification_to_dict,
    preferences_to_dict,
)

from narrative_agentic.stellar_outreach.mini_games_phase2 import (
    DiplomacyScenario,
    DiplomacyResult,
    SignalPuzzle,
    SignalDecodeResult,
    HarvestBoard,
    HarvestResult,
    SkyScannerSession,
    SkyScannerResult,
    generate_diplomacy_scenario,
    score_diplomacy,
    generate_signal_puzzle,
    score_signal_decode,
    generate_harvest_board,
    score_harvest,
    generate_sky_scanner_session,
    score_sky_scanner,
)

from narrative_agentic.stellar_outreach.friends import (
    FriendData,
    SynastryResult,
    get_friends,
    get_friend_requests,
    send_friend_request,
    respond_to_request,
    remove_friend,
    block_player,
    send_gift,
    calculate_compatibility,
    synastry_result_to_dict,
)

from narrative_agentic.stellar_outreach.streaks import (
    StreakData,
    MilestoneReward,
    get_streak,
    get_streak_rewards,
    checkin,
    purchase_freeze,
    claim_reward,
)

from narrative_agentic.stellar_outreach.npc_crew import (
    NpcRelationship,
    get_npc_list,
    get_npc_detail,
    interact_with_npc,
    gift_npc,
    get_active_perks,
)

from narrative_agentic.stellar_outreach.guilds import (
    GuildData,
    GuildMember,
    create_guild,
    get_guild,
    join_guild,
    leave_guild,
    generate_invite,
    contribute_resources as guild_contribute_resources,
    get_weekly_challenge,
    send_chat_message,
)

from narrative_agentic.stellar_outreach.star_atlas import (
    StarAtlasData,
    get_atlas,
    get_atlas_category,
    discover_object,
    get_mission_archive,
    add_mission_entry,
    get_cosmic_passport,
)

from narrative_agentic.stellar_outreach.station_customization import (
    CustomizationData,
    get_customization,
    get_available_skins,
    apply_skin,
    preview_skin,
    get_available_decorations,
    unlock_decoration,
    apply_decoration,
    remove_decoration,
    get_element_palette,
    force_unlock_skin,
)

from narrative_agentic.stellar_outreach.cosmetic_store import (
    PlayerWallet,
    get_store_catalog,
    get_featured_items,
    get_wallet,
    purchase_item,
    verify_iap_receipt,
    get_transaction_history,
    gift_store_item,
    get_gem_packs,
    get_store_summary,
)

from narrative_agentic.stellar_outreach.cosmic_pass import (
    CosmicPassData,
    get_pass_status,
    get_season_info,
    get_season_progress,
    get_season_rewards,
    get_pass_benefits,
    get_subscription_products,
    subscribe,
    verify_subscription_receipt,
    cancel_subscription,
    claim_tier_reward,
    earn_season_xp,
    claim_monthly_cosmetic,
    get_active_benefits,
)

__all__ = [
    # Discovery Cards
    "DiscoveryCard",
    "CardCollection",
    "fetch_daily_card",
    "get_card_collection",
    "collect_card",
    # Birth Chart Engine
    "BirthChartInput",
    "PlanetPosition",
    "NatalChart",
    "ZodiacArchetype",
    "PlayerProfile",
    "calculate_birth_chart",
    "player_profile_to_dict",
    # Transit Engine
    "TransitSnapshot",
    "TransitPlanetPosition",
    "AspectHit",
    "ModuleStatus",
    "CosmicBriefing",
    "get_transit_snapshot",
    "calculate_player_transits",
    "generate_briefing_text",
    "cosmic_briefing_to_dict",
    "transit_snapshot_to_dict",
    # Station Modules
    "StationModule",
    "PlayerStation",
    "create_station",
    "get_station",
    "save_station",
    "apply_cosmic_status",
    "collect_resources",
    "upgrade_module",
    "get_module_info",
    "station_to_dict",
    # Mini-Games (TASK-004)
    "ConstellationPuzzle",
    "StarPatternResult",
    "RepairGrid",
    "RepairResult",
    "AsteroidScenario",
    "DeflectionResult",
    "DailyMission",
    "generate_star_puzzle",
    "score_star_puzzle",
    "generate_repair_puzzle",
    "validate_repair_solution",
    "generate_asteroid_scenario",
    "score_deflection",
    "generate_daily_mission",
    "daily_mission_to_dict",
    # Cosmic Briefing (TASK-005)
    "DailyBriefingData",
    "generate_daily_briefing",
    "get_cached_briefing",
    "briefing_to_dict",
    "get_element_colors",
    "ELEMENT_COLORS",
    # Notifications (TASK-006)
    "NotificationPayload",
    "NotificationPreferences",
    "NotificationHistory",
    "generate_morning_briefing",
    "generate_event_notification",
    "generate_re_engagement",
    "can_send_notification",
    "get_preferences",
    "update_preferences",
    "record_app_open",
    "get_notification_history",
    "mark_notification_read",
    "get_daily_count",
    "notification_to_dict",
    "preferences_to_dict",
    # Phase 2 Mini-Games (TASK-008)
    "DiplomacyScenario",
    "DiplomacyResult",
    "SignalPuzzle",
    "SignalDecodeResult",
    "HarvestBoard",
    "HarvestResult",
    "SkyScannerSession",
    "SkyScannerResult",
    "generate_diplomacy_scenario",
    "score_diplomacy",
    "generate_signal_puzzle",
    "score_signal_decode",
    "generate_harvest_board",
    "score_harvest",
    "generate_sky_scanner_session",
    "score_sky_scanner",
    # Friends & Compatibility (TASK-010)
    "FriendData",
    "SynastryResult",
    "get_friends",
    "get_friend_requests",
    "send_friend_request",
    "respond_to_request",
    "remove_friend",
    "block_player",
    "send_gift",
    "calculate_compatibility",
    "synastry_result_to_dict",
    # Streaks (TASK-012)
    "StreakData",
    "MilestoneReward",
    "get_streak",
    "get_streak_rewards",
    "checkin",
    "purchase_freeze",
    "claim_reward",
    # NPC Crew (TASK-009)
    "NpcRelationship",
    "get_npc_list",
    "get_npc_detail",
    "interact_with_npc",
    "gift_npc",
    "get_active_perks",
    # Guilds (TASK-011)
    "GuildData",
    "GuildMember",
    "create_guild",
    "get_guild",
    "join_guild",
    "leave_guild",
    "generate_invite",
    "guild_contribute_resources",
    "get_weekly_challenge",
    "send_chat_message",
    # Star Atlas (TASK-013)
    "StarAtlasData",
    "get_atlas",
    "get_atlas_category",
    "discover_object",
    "get_mission_archive",
    "add_mission_entry",
    "get_cosmic_passport",
    # Station Customization (TASK-014)
    "CustomizationData",
    "get_customization",
    "get_available_skins",
    "apply_skin",
    "preview_skin",
    "get_available_decorations",
    "unlock_decoration",
    "apply_decoration",
    "remove_decoration",
    "get_element_palette",
    "force_unlock_skin",
    # Cosmetic Store & IAP (TASK-015)
    "PlayerWallet",
    "get_store_catalog",
    "get_featured_items",
    "get_wallet",
    "purchase_item",
    "verify_iap_receipt",
    "get_transaction_history",
    "gift_store_item",
    "get_gem_packs",
    "get_store_summary",
    # Cosmic Pass & Stellar Premium (TASK-016)
    "CosmicPassData",
    "get_pass_status",
    "get_season_info",
    "get_season_progress",
    "get_season_rewards",
    "get_pass_benefits",
    "get_subscription_products",
    "subscribe",
    "verify_subscription_receipt",
    "cancel_subscription",
    "claim_tier_reward",
    "earn_season_xp",
    "claim_monthly_cosmetic",
    "get_active_benefits",
]
